import { Arya } from 'next/font/google'

import './global.css';
import './styles.css';

const arya = Arya({
  weight: ["400", "700"],
  subsets: ['latin'],
  display: 'swap',
})

export const metadata = {
  title: 'Welcome to live-market',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en" className={arya.className}>
      <body>{children}</body>
    </html>
  );
}
